name: Package PR

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn

      - name: Build
        run: yarn build:packages

      - run: yarn dlx pkg-pr-new publish './packages/saas-ui-auth'
